version: "3"

services:
  api1:
    networks:
      - network-my-app
    container_name: api1
    build:
      context: ./packages/api1
      dockerfile: Dockerfile
    ports:
     - "3000:3000"
  api2:
    networks:
      - network-my-app
    container_name: api2
    build:
      context: ./packages/api2
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
    env_file:
     - ./packages/api2/.env
    depends_on:
     - api1
networks:
  network-my-app:
    driver: bridge
